/* logo.h - the LP mark, the wordmark's letters, the desktop's gradient,
 * and where and how fast the boot splash draws them, as tables for
 * splash.c - and for desktop/branding/lp-splash-fade, which draws the
 * session's first frame to match it (it defines u8, s16 and u16 first).
 *
 * GENERATED by desktop/branding/src/mark.py from the same shapes that
 * produce the SVGs in desktop/branding/logo - change them there and rerun
 * `python3 make.py` in desktop/branding, never by hand here, or the boot
 * screen and the logo files stop being the same drawing.
 *
 * A primitive is a round-ended straight stroke (LP_SEG: x0 y0 x1 y1) or a
 * circular stroke over whole quadrants (LP_ARC: cx cy r, quads = bit 0
 * top-right, 1 top-left, 2 bottom-left, 3 bottom-right), both with width w.
 * Units are 1/16 of a design unit; y grows downwards. `accent` picks
 * the orange instead of the ink colour. */
#ifndef LP_SPLASH_LOGO_H
#define LP_SPLASH_LOGO_H

enum { LP_SEG, LP_ARC };

typedef struct {
    u8  kind, quads, accent;
    s16 a, b, c, d, w;
} lp_prim_t;

#define LP_UNIT 16

/* The mark: ring first, the L drawn over its west side. Its box is
 * (3,1)-(13,15) in design units. */
#define LP_MARK_X0 48
#define LP_MARK_Y0 16
#define LP_MARK_X1 208
#define LP_MARK_Y1 240
static const lp_prim_t LP_MARK[] = {
    { LP_ARC, 0xf, 1, 112, 80, 48, 0, 32 },
    { LP_SEG, 0x0, 0, 64, 32, 64, 224, 32 },
    { LP_SEG, 0x0, 0, 64, 224, 192, 224, 32 },
};

/* The wordmark's letters, baseline at y=0, left stroke centre at x=0.
 * A letter's pen advance is adv + LP_TRACK; `kern` is added before it
 * is drawn (round-sided letters sit a little into the gap). A letter
 * not listed here is left as a space - add it to mark.py's GLYPHS. */
#define LP_TRACK 87
#define LP_CAP   245   /* cap height, outer edge to edge */
typedef struct { char ch; s16 adv, kern; u8 first, count; } lp_glyph_t;
static const lp_prim_t LP_LETTER_PRIMS[] = {
    { LP_SEG, 0x0, 0, 0, -64, 58, -64, 37 },
    { LP_SEG, 0x0, 0, 0, -208, 0, 0, 37 },
    { LP_SEG, 0x0, 0, 0, 0, 115, 0, 37 },
    { LP_SEG, 0x0, 0, 0, -208, 0, 0, 37 },
    { LP_SEG, 0x0, 0, 0, -208, 51, -208, 37 },
    { LP_SEG, 0x0, 0, 0, -96, 51, -96, 37 },
    { LP_ARC, 0x9, 0, 51, -152, 56, 0, 37 },
    { LP_SEG, 0x0, 0, 0, -64, 128, -64, 37 },
    { LP_ARC, 0x7, 0, 64, -64, 64, 0, 37 },
    { LP_SEG, 0x0, 0, 0, -128, 0, 0, 37 },
    { LP_SEG, 0x0, 1, 0, -205, 0, -205, 48 },
    { LP_SEG, 0x0, 0, 0, -208, 0, 0, 37 },
    { LP_SEG, 0x0, 0, 0, -128, 0, 0, 37 },
    { LP_ARC, 0x3, 0, 60, -68, 60, 0, 37 },
    { LP_SEG, 0x0, 0, 120, -68, 120, 0, 37 },
    { LP_ARC, 0xf, 0, 64, -64, 64, 0, 37 },
    { LP_SEG, 0x0, 0, 0, -128, 0, 0, 37 },
    { LP_ARC, 0x2, 0, 64, -64, 64, 0, 37 },
    { LP_SEG, 0x0, 0, 64, -128, 77, -128, 37 },
    { LP_SEG, 0x0, 0, 0, -128, 0, -60, 37 },
    { LP_ARC, 0xc, 0, 60, -60, 60, 0, 37 },
    { LP_SEG, 0x0, 0, 120, -128, 120, 0, 37 },
    { LP_SEG, 0x0, 0, 0, -128, 110, 0, 37 },
    { LP_SEG, 0x0, 0, 110, -128, 0, 0, 37 },
    { LP_SEG, 0x0, 0, 0, -128, 109, -128, 37 },
    { LP_SEG, 0x0, 0, 109, -128, 0, 0, 37 },
    { LP_SEG, 0x0, 0, 0, 0, 109, 0, 37 },
};
static const lp_glyph_t LP_LETTERS[] = {
    { '-', 58, 0, 0, 1 },
    { 'L', 115, 0, 1, 2 },
    { 'P', 107, 0, 3, 4 },
    { 'e', 128, -8, 7, 2 },
    { 'i', 0, 0, 9, 2 },
    { 'l', 0, 0, 11, 1 },
    { 'n', 120, 0, 12, 3 },
    { 'o', 128, -8, 15, 1 },
    { 'r', 77, 0, 16, 3 },
    { 'u', 120, 0, 19, 3 },
    { 'x', 110, 0, 22, 2 },
    { 'z', 109, 0, 24, 3 },
};

/* Colours, 8 bits per channel. */
#define LP_RGB_ACCENT { 0xf2, 0x8c, 0x28 }   /* #f28c28 */
#define LP_RGB_INK { 0xff, 0xff, 0xff }   /* #ffffff */
#define LP_RGB_WORD { 0xdb, 0xe8, 0xf0 }   /* #dbe8f0 */

/* The dark wallpaper's gradient (desktop/branding/src/wallpaper.py):
 * light from a point at LP_FOCUS_X, LP_FOCUS_Y (1/4096ths of the width
 * and height), and the colour at 65 evenly spaced distances from it, 0 at
 * the focus and 64 at the farthest corner, as 8.8 fixed-point sRGB. */
#define LP_FOCUS_X 410
#define LP_FOCUS_Y 82
#define LP_GRAD_N 65
static const u16 LP_GRAD[LP_GRAD_N][3] = {
    {  8960, 42496, 40960 }, {  8687, 41484, 40416 }, {  8411, 40460, 39858 }, {  8133, 39428, 39289 },
    {  7857, 38394, 38715 }, {  7585, 37363, 38139 }, {  7320, 36340, 37565 }, {  7064, 35329, 36998 },
    {  6820, 34335, 36442 }, {  6591, 33364, 35900 }, {  6378, 32419, 35377 }, {  6184, 31505, 34877 },
    {  6011, 30626, 34404 }, {  5859, 29787, 33962 }, {  5722, 28969, 33560 }, {  5596, 28164, 33193 },
    {  5480, 27370, 32857 }, {  5375, 26590, 32543 }, {  5282, 25822, 32246 }, {  5200, 25068, 31959 },
    {  5127, 24327, 31677 }, {  5063, 23601, 31392 }, {  5006, 22890, 31100 }, {  4955, 22195, 30795 },
    {  4906, 21516, 30472 }, {  4860, 20856, 30124 }, {  4812, 20215, 29748 }, {  4760, 19595, 29337 },
    {  4703, 18996, 28887 }, {  4639, 18421, 28393 }, {  4568, 17870, 27856 }, {  4503, 17337, 27308 },
    {  4442, 16820, 26754 }, {  4385, 16320, 26194 }, {  4330, 15834, 25628 }, {  4275, 15362, 25059 },
    {  4221, 14903, 24485 }, {  4165, 14455, 23909 }, {  4106, 14017, 23331 }, {  4045, 13589, 22750 },
    {  3980, 13169, 22169 }, {  3911, 12757, 21588 }, {  3836, 12351, 21007 }, {  3756, 11950, 20426 },
    {  3669, 11554, 19847 }, {  3576, 11160, 19270 }, {  3476, 10769, 18696 }, {  3369, 10380, 18125 },
    {  3256,  9993, 17554 }, {  3148,  9616, 16972 }, {  3045,  9248, 16381 }, {  2946,  8888, 15781 },
    {  2850,  8536, 15175 }, {  2757,  8191, 14563 }, {  2666,  7852, 13948 }, {  2575,  7517, 13331 },
    {  2486,  7187, 12713 }, {  2398,  6860, 12097 }, {  2312,  6535, 11483 }, {  2226,  6213, 10873 },
    {  2141,  5892, 10269 }, {  2055,  5571,  9672 }, {  1968,  5251,  9083 }, {  1881,  4930,  8504 },
    {  1792,  4608,  7936 },
};

/* Layout - shared with desktop/branding/lp-splash-fade, which draws the
 * session's first frame on the same pixels (see mark.py SPLASH_LAYOUT). */
#define LP_LAYOUT_MARK_H        15   /* the mark's height, % of the screen's height */
#define LP_LAYOUT_MARK_MAXW     22   /* ...but at most this % of its width (portrait panels) */
#define LP_LAYOUT_MARK_MIN      24   /* ...and at least this many pixels */
#define LP_LAYOUT_CENTRE_Y      44   /* the mark's centre, % down the screen: dead centre reads low */
#define LP_LAYOUT_WORD_CAP      27   /* the name's cap height, % of the mark's height */
#define LP_LAYOUT_WORD_GAP      62   /* the name's baseline, % of the mark's height below its bottom */
#define LP_LAYOUT_SPIN_Y        78   /* the spinner's centre, % down the screen */
#define LP_LAYOUT_SPIN_R        80   /* the spinner's radius (to the stroke's centre), per mille of the mark */
#define LP_LAYOUT_SPIN_W        18   /* the spinner's stroke, per mille of the mark's height */
#define LP_LAYOUT_OEM_MARK_H     6   /* under a PC maker's logo (ACPI BGRT): the mark's height, % of the screen's */
#define LP_LAYOUT_OEM_CENTRE_Y    84   /* ...its centre, % down the screen - near the bottom, as Ubuntu's */
#define LP_LAYOUT_OEM_SPIN_Y    70   /* ...the spinner, when the maker's logo has no known bottom */

/* Motion (mark.py SPLASH_MOTION; design/feel.md §2). */
#define LP_MOTION_LOGO_IN_MS        400   /* the logo fading in */
#define LP_MOTION_SPIN_DELAY_MS    1000   /* held back after the logo: a fast boot never shows it */
#define LP_MOTION_SPIN_IN_MS        260   /* the spinner arriving (the sheet spring) */
#define LP_MOTION_SPIN_OUT_MS       182   /* and leaving: 0.7x */
#define LP_MOTION_SPIN_TURN_MS     1300   /* one revolution */
#define LP_MOTION_REDUCED_MS        100   /* any change, when motion is reduced: a crossfade this long */
#define LP_MOTION_PULSE_MS         2400   /* reduced motion's stand-in for turning: a slow brightness pulse */
#define LP_MOTION_HOLD_MS         90000   /* give up waiting for the desktop and hand the screen back */

/* w for each of those springs (critically damped, settled by the time
 * above under lp-motion.c's rule), in 1/16 rad/s. */
#define LP_W16_LOGO_IN      324   /* 400 ms */
#define LP_W16_SPIN_IN      533   /* 260 ms */
#define LP_W16_SPIN_OUT     802   /* 182 ms */
#define LP_W16_REDUCED     1581   /* 100 ms */

/* LP_WAVE[i]: (1 - cos(pi i/64)) / 2 in 0..65535 - a smooth rise from 0 to
 * 1: reduced motion's breathing, run forwards then backwards, and the
 * cosine the spinner's head is placed with. */
static const u16 LP_WAVE[65] = {
        0,    39,   158,   355,   630,   982,  1411,  1915,  2494,  3146,  3869,  4662,  5522,
     6448,  7438,  8488,  9597, 10762, 11980, 13248, 14563, 15922, 17321, 18758, 20228, 21728,
    23256, 24806, 26375, 27960, 29556, 31160, 32767, 34375, 35979, 37575, 39160, 40729, 42279,
    43807, 45307, 46777, 48214, 49613, 50972, 52287, 53555, 54773, 55938, 57047, 58097, 59087,
    60013, 60873, 61666, 62389, 63041, 63620, 64124, 64553, 64905, 65180, 65377, 65496, 65535,
};

/* LP_ATAN[i]: atan(i/64) in 1/65536ths of a turn (0..8192, i.e. 0..45
 * degrees) - enough, with the octant, to give every pixel of the spinner
 * its angle without floating point. */
static const u16 LP_ATAN[65] = {
        0,   163,   326,   489,   651,   813,   975,  1136,  1297,  1457,  1617,  1775,  1933,
     2090,  2246,  2401,  2555,  2708,  2860,  3010,  3159,  3307,  3453,  3599,  3742,  3884,
     4025,  4164,  4302,  4438,  4572,  4705,  4836,  4966,  5094,  5220,  5344,  5467,  5589,
     5708,  5826,  5943,  6058,  6171,  6282,  6392,  6500,  6607,  6712,  6815,  6917,  7018,
     7117,  7214,  7310,  7405,  7498,  7589,  7679,  7768,  7856,  7942,  8026,  8110,  8192,
};

#endif
