"""icons.py - the LP icon theme: app tiles for the dock, symbolic icons for the bar.

Two families with opposite jobs, so they are drawn by opposite rules.

The APP ICONS are what the owner's mockup shows down the dock: a column
of colourful rounded squares with one white symbol each. They share one
tile - the same 112-unit square with the same 26-unit corners as the LP
mark's own tile (mark.tile_body), on a 128 grid - so the logo sits in the
dock as one of the family rather than a guest. Each app gets its own hue,
light at the top left and deeper at the bottom right, which is the same
direction the light falls on the wallpaper. The symbols are drawn with
one pen: a 9-unit stroke with round ends, the ratio the mark itself uses
(its 2-unit stroke on a 14-unit height). One symbol per tile and nothing
written on it, because the dock shows these at 48 logical pixels and an
icon that needs reading at that size is a label that failed.

A hue belongs to one app. Two blue tiles side by side in a dock are the
same app to a glance, so the hues are spread round the wheel and the
neutrals (graphite, slate, paper) are kept for the tools whose real-world
object is itself neutral - a terminal, a calculator, a clock face.

The SYMBOLIC ICONS are the top bar's status icons: Wi-Fi, volume,
battery, power, the on-screen keyboard's button. GTK recolours them to
the text colour, and it does it by forcing `fill` on every path, rect and
circle in the file. So they are filled outlines only - a stroked line
would come out as a solid blob - and the "empty" part of a level icon is
the same shape at opacity .35, which GTK leaves alone. They are drawn on
the 16-unit grid with edges on half units: on the XPS the bar runs at
scale 2, where half a unit is one whole physical pixel, so every edge is
sharp there, and at scale 1 they are no softer than Adwaita's.

Names: every icon is written once under the freedesktop name the
standard gives it (utilities-terminal, accessories-calculator ...) and
then linked under the names the base's Debian applications actually ask
for (foot, org.gnome.Calculator ...) and under our own programs' names.
Links rather than copies, so an edit cannot reach one name and miss
another. Anything we do not draw falls through Inherits= to Papirus-Dark,
which the base already carries and which the desktop used before this
theme existed.
"""

import math
import os

from geom import Seg, Arc, fmt, rrect_path, circle_path
import mark

TILE = 128
INSET = 8
RADIUS = 26
PEN = 9          # the app symbols' stroke

# ── app tiles ────────────────────────────────────────────────────────────


def _grad(uid, top, bottom):
    return (f'    <linearGradient id="{uid}" x1="0" y1="0" x2=".35" y2="1">\n'
            f'      <stop offset="0" stop-color="{top}"/>\n'
            f'      <stop offset="1" stop-color="{bottom}"/>\n'
            f'    </linearGradient>\n')


def tile_svg(name, what, top, bottom, glyph, rim=0.30):
    """One app icon: the tile in its two colours, the lit rim every tile
    shares, and the symbol with a soft shadow under it.

    The rim is a hairline of white along the top edge that fades out by
    the middle - how a rounded object catches light from above. It is
    what keeps a dark tile (terminal, calculator) from sinking into the
    dark dock behind it. The symbol's shadow is the symbol again, black
    at 18%, two units lower: at 48px that is under one pixel, which reads
    as the symbol sitting on the tile rather than printed into it."""
    t = TILE - 2 * INSET
    uid = name.replace(".", "_").replace("-", "_")
    body = (f'<!-- {name} - generated by desktop/branding/src/icons.py; edit that, not this.\n'
            f'     {what} -->\n'
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {TILE} {TILE}" width="{TILE}" height="{TILE}">\n'
            f'  <defs>\n'
            + _grad(uid + "_bg", top, bottom) +
            f'    <linearGradient id="{uid}_hl" x1="0" y1="0" x2="0" y2="1">\n'
            f'      <stop offset="0" stop-color="#fff" stop-opacity="{rim}"/>\n'
            f'      <stop offset=".5" stop-color="#fff" stop-opacity="0"/>\n'
            f'    </linearGradient>\n'
            f'    <clipPath id="{uid}_clip"><path d="{rrect_path(INSET, INSET, t, t, RADIUS)}"/></clipPath>\n'
            f'  </defs>\n'
            f'  <path fill="url(#{uid}_bg)" d="{rrect_path(INSET, INSET, t, t, RADIUS)}"/>\n')
    back = glyph.get("back")
    if back:
        body += f'  <g clip-path="url(#{uid}_clip)">\n{back(uid)}  </g>\n'
    hw = 1.5
    body += (f'  <path fill="url(#{uid}_hl)" fill-rule="evenodd" d="'
             f'{rrect_path(INSET, INSET, t, t, RADIUS)}'
             f'{rrect_path(INSET + hw, INSET + hw, t - 2 * hw, t - 2 * hw, RADIUS - hw)}"/>\n')
    if glyph.get("shadow", True):
        body += (f'  <g opacity=".18" transform="translate(0 2)">\n'
                 f'{glyph["draw"](True)}  </g>\n')
    body += glyph["draw"](False)
    body += '</svg>\n'
    return body


def _stroke(d, colour, w=PEN, extra=""):
    return (f'    <path d="{d}" fill="none" stroke="{colour}" stroke-width="{fmt(w)}" '
            f'stroke-linecap="round" stroke-linejoin="round"{extra}/>\n')


def _fill(d, colour, extra=""):
    return f'    <path d="{d}" fill="{colour}"{extra}/>\n'


def _circle(cx, cy, r, colour, extra=""):
    return f'    <circle cx="{fmt(cx)}" cy="{fmt(cy)}" r="{fmt(r)}" fill="{colour}"{extra}/>\n'


def _ring(cx, cy, r, colour, w=PEN):
    return (f'    <circle cx="{fmt(cx)}" cy="{fmt(cy)}" r="{fmt(r)}" fill="none" '
            f'stroke="{colour}" stroke-width="{fmt(w)}"/>\n')


def _rr(x, y, w, h, r, colour, extra=""):
    return _fill(rrect_path(x, y, w, h, r), colour, extra)


def _pick(sh, colour):
    """The shadow pass draws every colour black."""
    return "#000" if sh else colour


W = "#ffffff"


def g_terminal():
    # a prompt: the chevron in white, the cursor in the mockup's green
    def draw(sh):
        return (_stroke("M36 44L56 62L36 80", _pick(sh, W), 10) +
                _stroke("M66 82H92", _pick(sh, "#5be38f"), 10))
    return {"draw": draw}


def g_files():
    # a folder: the back sheet with its tab, a lighter front sheet over it
    def draw(sh):
        back = ("M28 42a8 8 0 0 1 8-8h18a8 8 0 0 1 6.4 3.2L64 42H92a8 8 0 0 1 8 8V90"
                "a8 8 0 0 1-8 8H36a8 8 0 0 1-8-8Z")
        return (_fill(back, _pick(sh, W), "" if sh else ' opacity=".62"') +
                _rr(28, 52, 72, 46, 8, _pick(sh, W)))
    return {"draw": draw}


def _page(x, y, w, h, fold, colour):
    """A sheet with its top right corner folded, as one path."""
    return _fill(f"M{x + 7} {y}H{x + w - fold}L{x + w} {y + fold}V{y + h - 7}"
                 f"a7 7 0 0 1-7 7H{x + 7}a7 7 0 0 1-7-7V{y + 7}a7 7 0 0 1 7-7Z", colour)


def g_text_editor(line):
    # a page of text, and a pencil across its corner
    def draw(sh):
        s = _page(34, 26, 54, 72, 16, _pick(sh, W))
        if not sh:
            for i, x1 in enumerate((62, 76, 64, 72)):
                s += _stroke(f"M46 {50 + i * 11}H{x1}", line, 6)
        # the pencil: body, then the sharpened end
        pen = "M100 60L70 90"
        s += _stroke(pen, _pick(sh, "#1f2937"), 17)
        s += _stroke(pen, _pick(sh, "#ffc53d"), 10)
        s += _fill("M66.2 84.6L75.4 93.8L63 97Z", _pick(sh, "#1f2937"))
        return s
    return {"draw": draw}


def g_code():
    def draw(sh):
        c = _pick(sh, W)
        return (_stroke("M46 42L26 64L46 86", c) + _stroke("M82 42L102 64L82 86", c) +
                _stroke("M71 36L57 92", c, 8))
    return {"draw": draw}


def g_browser():
    # a globe: the rim, one meridian, the equator and two parallels
    def draw(sh):
        c = _pick(sh, W)
        r = 34
        s = _ring(64, 64, r, c, 8)
        s += (f'    <ellipse cx="64" cy="64" rx="14" ry="{r}" fill="none" stroke="{c}" '
              f'stroke-width="6"/>\n')
        s += _stroke("M31 64H97", c, 6)
        for y in (47, 81):
            hw = math.sqrt(r * r - (y - 64) ** 2) - 2
            s += _stroke(f"M{fmt(64 - hw)} {y}H{fmt(64 + hw)}", c, 5)
        return s
    return {"draw": draw}


def g_mail(flap):
    def draw(sh):
        s = _rr(24, 36, 80, 56, 10, _pick(sh, W))
        if not sh:
            s += _stroke("M30 44L64 68L98 44", flap, 7)
        return s
    return {"draw": draw}


def g_calculator():
    # the four operations, equals in the accent
    def draw(sh):
        c = _pick(sh, W)
        a, b, k = 44, 84, 12
        return (_stroke(f"M{a - k} {a}H{a + k}M{a} {a - k}V{a + k}", c, 8) +
                _stroke(f"M{b - k} {a}H{b + k}", c, 8) +
                _stroke(f"M{a - 9} {b - 9}L{a + 9} {b + 9}M{a + 9} {b - 9}L{a - 9} {b + 9}", c, 8) +
                _stroke(f"M{b - k} {b - 6}H{b + k}M{b - k} {b + 6}H{b + k}",
                        _pick(sh, mark.ORANGE), 8))
    return {"draw": draw}


def g_spreadsheet(line):
    def draw(sh):
        s = _rr(26, 30, 76, 68, 9, _pick(sh, W))
        if not sh:
            s += _rr(26, 30, 76, 17, 9, line, ' opacity=".28"')
            s += _fill("M26 44H102V47H26Z", line, ' opacity=".28"')
            for x in (51, 76):
                s += _stroke(f"M{x} 34V94", line, 3.5)
            for y in (47, 64, 81):
                s += _stroke(f"M30 {y}H98", line, 3.5)
        return s
    return {"draw": draw}


def g_store(line):
    # a shopping bag
    def draw(sh):
        s = _stroke("M48 52V44a16 16 0 0 1 32 0V52", _pick(sh, W), 8)
        s += _fill("M34 50H94a6 6 0 0 1 6 6.6L97 94a8 8 0 0 1-8 7H39a8 8 0 0 1-8-7L28 56.6"
                   "A6 6 0 0 1 34 50Z", _pick(sh, W))
        if not sh:
            s += _stroke("M52 66a12 12 0 0 0 24 0", line, 7)
        return s
    return {"draw": draw}


def g_monitor():
    def draw(sh):
        s = ""
        if not sh:
            for y in (44, 64, 84):
                s += _stroke(f"M26 {y}H102", "#ffffff", 2, ' opacity=".14"')
        s += _stroke("M26 78H42L52 50L66 92L78 38L88 70H102", _pick(sh, "#4ee89a"), 8)
        return s
    return {"draw": draw}


def _gear_path(cx, cy, r_out, r_in, teeth, tooth_w, r_hole):
    """A gear as one path: the rim alternates between the tooth tops and
    the valleys, with the hole cut out by winding the other way."""
    pts = []
    n = teeth * 4
    half = math.degrees(tooth_w / 2 / r_out)
    for i in range(teeth):
        a = 360 / teeth * i
        for ang, rad in ((a - 360 / teeth / 2 + half * 1.6, r_in), (a - half, r_out),
                         (a + half, r_out), (a + 360 / teeth / 2 - half * 1.6, r_in)):
            t = math.radians(ang - 90)
            pts.append((cx + rad * math.cos(t), cy + rad * math.sin(t)))
    d = "M" + "L".join(f"{fmt(x)} {fmt(y)}" for x, y in pts) + "Z"
    return d + circle_path(cx, cy, r_hole, ccw=True)


def g_settings():
    def draw(sh):
        d = _gear_path(64, 64, 38, 29, 8, 14, 12)
        c = _pick(sh, W)
        return (f'    <path d="{d}" fill="{c}" stroke="{c}" stroke-width="3" '
                f'stroke-linejoin="round" fill-rule="evenodd"/>\n')
    return {"draw": draw}


def g_clock():
    def draw(sh):
        ink = _pick(sh, "#2b2f38")
        s = ""
        for i in range(12):
            a = math.radians(i * 30)
            r0 = 30 if i % 3 else 27
            s += _stroke(f"M{fmt(64 + r0 * math.sin(a))} {fmt(64 - r0 * math.cos(a))}"
                         f"L{fmt(64 + 36 * math.sin(a))} {fmt(64 - 36 * math.cos(a))}",
                         ink, 5 if i % 3 == 0 else 3, "" if i % 3 == 0 or sh else ' opacity=".55"')
        s += _stroke("M64 64L64 40", ink, 7)
        s += _stroke("M64 64L82 75", ink, 6)
        s += _stroke("M58 73L73 47", _pick(sh, mark.ORANGE_ON_LIGHT), 3)
        s += _circle(64, 64, 5, _pick(sh, mark.ORANGE_ON_LIGHT))
        return s
    return {"draw": draw, "shadow": False}


def g_calendar():
    # a page from a desk calendar: the red header is the tile's own top,
    # drawn behind the rim so the tile keeps its one silhouette
    def back(uid):
        return (f'    <path d="M0 0H128V46H0Z" fill="url(#{uid}_red)"/>\n')

    def draw(sh):
        if sh:
            return ""
        s = ""
        for x in (46, 82):
            s += _rr(x - 4, 22, 8, 16, 4, "#ffffff", ' opacity=".9"')
        grid = [(r, c) for r in range(3) for c in range(4)]
        for r, c in grid:
            x, y = 37 + c * 18, 62 + r * 16
            col = mark.ORANGE_ON_LIGHT if (r, c) == (1, 2) else "#3a3f4b"
            op = "" if (r, c) == (1, 2) else ' opacity=".7"'
            s += _rr(x - 6, y - 5, 12, 10, 3, col, op)
        return s
    return {"draw": draw, "back": back, "shadow": False}


def g_image():
    def draw(sh):
        s = _fill("M22 94L50 58a4 4 0 0 1 6.2-.2L72 78L82 66a4 4 0 0 1 6 0L106 94Z", _pick(sh, W))
        s += _circle(86, 42, 10, _pick(sh, "#ffe46b"))
        return s
    return {"draw": draw}


def g_document(line):
    def draw(sh):
        s = _page(36, 24, 56, 80, 17, _pick(sh, W))
        if not sh:
            s += _rr(46, 48, 36, 18, 4, line, ' opacity=".35"')
            for i, x1 in enumerate((82, 82, 70)):
                s += _stroke(f"M48 {76 + i * 10}H{x1}", line, 5, ' opacity=".6"')
        return s
    return {"draw": draw}


def g_archive(line):
    def draw(sh):
        s = _rr(24, 32, 80, 20, 6, _pick(sh, W))
        s += _rr(30, 55, 68, 43, 7, _pick(sh, W))
        if not sh:
            s += _stroke("M56 66H72", line, 7)
        return s
    return {"draw": draw}


def g_video():
    def draw(sh):
        c = _pick(sh, W)
        return (f'    <path d="M52 40L90 64L52 88Z" fill="{c}" stroke="{c}" stroke-width="12" '
                f'stroke-linejoin="round"/>\n')
    return {"draw": draw}


def g_screenshot():
    def draw(sh):
        c = _pick(sh, W)
        s = ""
        for (x, y, dx, dy) in ((30, 30, 1, 1), (98, 30, -1, 1), (30, 98, 1, -1), (98, 98, -1, -1)):
            s += _stroke(f"M{x} {y + 16 * dy}V{y}H{x + 16 * dx}", c, 8)
        s += _circle(64, 64, 13, c)
        return s
    return {"draw": draw}


def g_installer():
    # into the machine: an arrow in the accent coming down into a tray
    def draw(sh):
        return (_stroke("M30 78V92a6 6 0 0 0 6 6H92a6 6 0 0 0 6-6V78", _pick(sh, W)) +
                _stroke("M64 30V76M46 60L64 78L82 60", _pick(sh, mark.ORANGE)))
    return {"draw": draw}


def g_disks(line):
    def draw(sh):
        s = _rr(24, 38, 80, 52, 11, _pick(sh, W))
        if not sh:
            s += _stroke("M26 72H102", line, 3, ' opacity=".35"')
            s += _circle(89, 81, 4, "#35c96b")
            s += _stroke("M36 81H62", line, 4, ' opacity=".5"')
        return s
    return {"draw": draw}


def g_keyboard(line):
    def draw(sh):
        s = _rr(20, 38, 88, 56, 10, _pick(sh, W))
        if not sh:
            for r, n in ((0, 7), (1, 6)):
                x0 = 29 + r * 5
                for i in range(n):
                    s += _rr(x0 + i * 11, 47 + r * 12, 8, 8, 2, line, ' opacity=".75"')
            s += _rr(40, 72, 48, 9, 3, line, ' opacity=".75"')
        return s
    return {"draw": draw}


# (canonical name, what, top, bottom, glyph, aliases)
# Aliases: the names Debian's own .desktop files ask for (checked against
# the base's /usr/share/applications), the other common names for the
# same kind of app, and our programs' names.
APPS = [
    ("utilities-terminal", "Terminal.", "#454a57", "#191b21", g_terminal(),
     ["foot", "org.codeberg.dnkl.foot", "terminal", "lp-terminal",
      "org.gnome.Terminal", "gnome-terminal", "xterm", "Alacritty"]),
    ("system-file-manager", "Files.", "#6f9bff", "#3150e0", g_files(),
     ["lp-files", "org.gnome.Nautilus", "nautilus", "file-manager", "thunar",
      "org.xfce.thunar", "pcmanfm"]),
    ("accessories-text-editor", "Text editor.", "#3fdcc7", "#0d8a8c",
     g_text_editor("#1aa3a0"),
     ["org.gnome.gedit", "gedit", "org.gnome.TextEditor", "text-editor",
      "gnome-text-editor", "mousepad", "org.xfce.mousepad"]),
    ("lp-code", "Code editor.", "#a98dff", "#5b36d6", g_code(),
     ["geany", "org.geany.Geany", "code", "com.visualstudio.code", "vscodium",
      "com.vscodium.codium", "accessories-code-editor", "gvim", "vim",
      "org.gnome.Builder", "applications-development"]),
    ("web-browser", "Web browser.", "#ffa347", "#d8336e", g_browser(),
     ["firefox-esr", "firefox", "org.mozilla.firefox", "internet-web-browser",
      "chromium", "org.chromium.Chromium", "epiphany", "org.gnome.Epiphany"]),
    ("internet-mail", "Mail.", "#5fcbff", "#1b7fd6", g_mail("#2a8fe0"),
     ["thunderbird", "org.mozilla.Thunderbird", "mail-client", "evolution",
      "org.gnome.Evolution", "claws-mail", "geary", "org.gnome.Geary"]),
    ("lp-notes", "Notes.", "#ffe27a", "#f5a524", None,
     ["gnote", "org.gnome.Gnote", "accessories-notes", "notes",
      "org.gnome.Notes", "xpad", "org.gnome.gnote"]),
    ("accessories-calculator", "Calculator.", "#555b69", "#23262d", g_calculator(),
     ["org.gnome.Calculator", "gnome-calculator", "calc", "galculator", "kcalc"]),
    ("x-office-spreadsheet", "Spreadsheet.", "#4fe08a", "#12994a",
     g_spreadsheet("#16a34a"),
     ["libreoffice-calc", "org.libreoffice.LibreOffice.calc", "gnumeric",
      "org.gnome.Gnumeric", "lp-spreadsheet", "office-spreadsheet"]),
    ("system-software-install", "Software.", "#ff8f57", "#e2481f",
     g_store("#e8552a"),
     ["lp-software", "org.gnome.Software", "gnome-software", "software-store",
      "synaptic", "system-software-update", "software-properties"]),
    ("utilities-system-monitor", "System monitor.", "#2e3a4f", "#0c1320", g_monitor(),
     ["lp-tasks", "org.gnome.SystemMonitor", "gnome-system-monitor", "htop",
      "system-monitor", "ksysguard"]),
    ("preferences-system", "Settings.", "#aab2c0", "#5b6474", g_settings(),
     ["lp-settings", "org.gnome.Settings", "gnome-control-center",
      "preferences-desktop", "systemsettings", "lp-quick", "settings"]),
    ("org.gnome.clocks", "Clock.", "#ffffff", "#dde0e6", g_clock(),
     ["gnome-clocks", "clock", "lp-clock", "alarm-clock", "preferences-system-time",
      "time-admin"]),
    ("office-calendar", "Calendar.", "#ffffff", "#e3e5ea", g_calendar(),
     ["org.gnome.Calendar", "gnome-calendar", "lp-calendar", "x-office-calendar",
      "calendar"]),
    ("image-viewer", "Image viewer.", "#34d6ef", "#0a7fb4", g_image(),
     ["org.gnome.eog", "eog", "org.gnome.Loupe", "loupe", "org.gnome.gThumb",
      "gthumb", "ristretto", "org.xfce.ristretto", "shotwell", "multimedia-photo-viewer"]),
    ("document-viewer", "Document viewer.", "#ff7474", "#d42330",
     g_document("#d42330"),
     ["org.gnome.Evince", "evince", "org.gnome.Papers", "atril", "okular",
      "org.kde.okular", "zathura", "office-document-viewer", "x-office-document"]),
    ("archive-manager", "Archive manager.", "#dba46a", "#8f5a2c", g_archive("#9a6232"),
     ["org.gnome.FileRoller", "file-roller", "ark", "org.kde.ark",
      "engrampa", "xarchiver", "utilities-archiver"]),
    ("multimedia-video-player", "Video player.", "#ec84f7", "#a321c6", g_video(),
     ["mpv", "io.mpv.Mpv", "video-player", "totem", "org.gnome.Totem", "vlc",
      "celluloid", "io.github.celluloid_player.Celluloid", "applications-multimedia"]),
    ("applets-screenshooter", "Screenshot.", "#bdf05d", "#5e9d0c", g_screenshot(),
     ["lp-shot", "org.gnome.Screenshot", "gnome-screenshot", "screenshot",
      "accessories-screenshot", "flameshot", "org.flameshot.Flameshot"]),
    ("system-installer", "Install LP.", mark.AUBERGINE["500"], mark.AUBERGINE["800"],
     g_installer(),
     ["lp-installer", "lp-install", "calamares", "ubiquity", "debian-installer",
      "system-os-installer"]),
    ("org.gnome.DiskUtility", "Disks.", "#7b8aa3", "#343f53", g_disks("#394660"),
     ["gnome-disks", "lp-disks", "disk-utility", "gparted", "partitionmanager",
      "drive-harddisk-system"]),
    ("lp-osk", "On-screen keyboard.", "#5b6070", "#262a33", g_keyboard("#2c313c"),
     ["onboard", "org.onboard.Onboard", "sm.puri.Squeekboard", "squeekboard",
      "florence", "accessories-on-screen-keyboard", "input-keyboard",
      "preferences-desktop-keyboard"]),
]


def g_notes():
    # a checklist, in brown ink - white on yellow is too faint to read
    ink = "#6b4700"

    def draw(sh):
        c = _pick(sh, ink)
        s = ""
        for i in range(3):
            y = 44 + i * 20
            if i == 0:
                s += _stroke(f"M30 {y}L35 {y + 5}L44 {y - 5}", c, 6)
            else:
                s += (f'    <circle cx="37" cy="{y}" r="5.5" fill="none" stroke="{c}" '
                      f'stroke-width="4.5"/>\n')
            s += _stroke(f"M54 {y}H{98 if i != 1 else 88}", c, 7,
                         ' opacity=".45"' if i == 0 and not sh else "")
        return s
    return {"draw": draw, "shadow": False}


APPS = [(n, w, t, b, g if g else g_notes(), a) for n, w, t, b, g, a in APPS]


def _calendar_red():
    return ('    <linearGradient id="{uid}_red" x1="0" y1="0" x2=".35" y2="1">\n'
            '      <stop offset="0" stop-color="#ff6464"/>\n'
            '      <stop offset="1" stop-color="#d92735"/>\n'
            '    </linearGradient>\n')


def app_svg(name, what, top, bottom, glyph):
    s = tile_svg(name, what, top, bottom, glyph)
    if name == "office-calendar":
        uid = name.replace(".", "_").replace("-", "_")
        s = s.replace("  </defs>\n", _calendar_red().format(uid=uid) + "  </defs>\n", 1)
    return s


# ── symbolic icons ───────────────────────────────────────────────────────
#
# Everything below is a filled outline (see the top of the file for why).
# Helpers return path data; sym() wraps a list of (d, opacity) in an SVG.

DIM = ".35"


def sector(cx, cy, r0, r1, a0, a1):
    """An annular sector, angles in visual degrees (0 east, 90 north),
    swept counter-clockwise from a0 to a1. r0 = 0 gives a wedge."""
    def pt(a, r):
        t = math.radians(a)
        return cx + r * math.cos(t), cy - r * math.sin(t)
    large = 1 if (a1 - a0) % 360 > 180 else 0
    o0, o1 = pt(a0, r1), pt(a1, r1)
    f = fmt
    d = f"M{f(o0[0])} {f(o0[1])}A{f(r1)} {f(r1)} 0 {large} 0 {f(o1[0])} {f(o1[1])}"
    if r0 <= 0:
        return d + f"L{f(cx)} {f(cy)}Z"
    i0, i1 = pt(a0, r0), pt(a1, r0)
    return d + f"L{f(i1[0])} {f(i1[1])}A{f(r0)} {f(r0)} 0 {large} 1 {f(i0[0])} {f(i0[1])}Z"


def arc_stroke(cx, cy, r, w, a0, a1):
    """A round-ended stroke along a circle from a0 to a1 (visual degrees,
    counter-clockwise), as a filled outline."""
    h = w / 2

    def pt(a, rr):
        t = math.radians(a)
        return cx + rr * math.cos(t), cy - rr * math.sin(t)
    large = 1 if (a1 - a0) % 360 > 180 else 0
    o0, o1 = pt(a0, r + h), pt(a1, r + h)
    i0, i1 = pt(a0, r - h), pt(a1, r - h)
    f = fmt
    return (f"M{f(o0[0])} {f(o0[1])}A{f(r + h)} {f(r + h)} 0 {large} 0 {f(o1[0])} {f(o1[1])}"
            f"A{f(h)} {f(h)} 0 0 0 {f(i1[0])} {f(i1[1])}"
            f"A{f(r - h)} {f(r - h)} 0 {large} 1 {f(i0[0])} {f(i0[1])}"
            f"A{f(h)} {f(h)} 0 0 0 {f(o0[0])} {f(o0[1])}Z")


def seg(x0, y0, x1, y1, w):
    return Seg(x0, y0, x1, y1, w).path()


def rr(x, y, w, h, r):
    return rrect_path(x, y, w, h, r)


class Badge(str):
    """Path data for a badge (a cross, a slash) laid over an icon. The
    rest of the icon is cut back around it - see sym()."""


def sym(name, what, parts, cut=None):
    """An SVG of filled paths. A part is path data, or (data, opacity);
    data starting "evenodd:" is filled even-odd, for holes.

    `cut` is path data for a region to keep clear around a Badge: at
    16px a cross drawn straight over the Wi-Fi fan merges into it, so
    everything that is not a badge is clipped to the square minus that
    region, leaving a one-unit gap round the badge. GTK's recolouring
    forces the fill of paths, but a clip path is geometry, not paint, so
    it survives."""
    body = (f'<!-- {name} - generated by desktop/branding/src/icons.py; edit that, not this.\n'
            f'     {what} -->\n'
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">\n')
    if cut:
        body += (f'  <defs><clipPath id="cut"><path clip-rule="evenodd" '
                 f'd="M-1 -1H17V17H-1Z{cut}"/></clipPath></defs>\n')
    for p in parts:
        d, op = p if isinstance(p, tuple) else (p, None)
        clip = ' clip-path="url(#cut)"' if cut and not isinstance(d, Badge) else ""
        rule = ' fill-rule="evenodd"' if d.startswith("evenodd:") else ""
        d = d.replace("evenodd:", "")
        o = f' opacity="{op}"' if op else ""
        body += f'  <path fill="#bebebe"{rule}{o}{clip} d="{d}"/>\n'
    return body + "</svg>\n"


# Wi-Fi: a fan of three bands over a wedge, opening upwards. Levels light
# the wedge and then one band per step; the rest stay at DIM, so the
# shape of the icon never changes and only its fill does.
WIFI_C = (8, 13.5)
WIFI_SPREAD = (48.5, 131.5)
WIFI_BANDS = [(0, 3.2), (4.6, 6.6), (8.0, 10.0), (11.4, 13.4)]


def wifi(level, dim_all=False):
    cx, cy = WIFI_C
    a0, a1 = WIFI_SPREAD
    out = []
    for i, (r0, r1) in enumerate(WIFI_BANDS):
        on = (i <= level) and not dim_all
        out.append((sector(cx, cy, r0, r1, a0, a1), None if on else DIM))
    return out


def badge_x(cx, cy, s=2.2, w=1.5):
    return Badge(seg(cx - s, cy - s, cx + s, cy + s, w) + seg(cx + s, cy - s, cx - s, cy + s, w))


def x_cut(cx, cy, s=2.2, w=1.5):
    """The clear region round badge_x: its square, one unit bigger."""
    h = s + w / 2 + 1
    return rr(cx - h, cy - h, 2 * h, 2 * h, 1.5)


def wifi_icons():
    out = {}
    for lvl, name in enumerate(("weak", "ok", "good", "excellent")):
        out[f"network-wireless-signal-{name}-symbolic"] = (
            f"Wi-Fi, {name} signal.", wifi(lvl))
    out["network-wireless-signal-none-symbolic"] = ("Wi-Fi, no signal.", wifi(-1))
    out["network-wireless-symbolic"] = ("Wi-Fi.", wifi(3))
    out["network-wireless-connected-symbolic"] = ("Wi-Fi, connected.", wifi(3))
    # acquiring: the fan dimmed, and three dots where the wedge was
    acq = wifi(-1)[1:]
    for x in (4.5, 8, 11.5):
        acq.append(circle_path(x, 13.25, 1.25))
    out["network-wireless-acquiring-symbolic"] = ("Wi-Fi, connecting.", acq)
    # offline (the radio is on and nothing is joined): dim fan, a cross
    # cut into its lower right. The cut is a gap in the fan, so the cross
    # reads at 16px instead of merging into the bands.
    off = []
    for p, op in wifi(-1):
        off.append((p, op))
    off.append(badge_x(12.5, 12.5, 2.0, 1.6))
    cut = x_cut(12.5, 12.5, 2.0, 1.6)
    out["network-wireless-offline-symbolic"] = ("Wi-Fi, not connected.", off, cut)
    out["network-wireless-no-route-symbolic"] = ("Wi-Fi, no internet.", off, cut)
    # disabled (radio off): the dim fan and a slash through it, with the
    # fan cut back a unit either side of the slash
    dis = wifi(-1)
    dis.append(Badge(seg(2.5, 2.5, 13.5, 13.5, 1.6)))
    slash_cut = Seg(1.5, 1.5, 14.5, 14.5, 3.6).path()
    out["network-wireless-disabled-symbolic"] = ("Wi-Fi turned off.", dis, slash_cut)
    out["network-wireless-hardware-disabled-symbolic"] = ("Wi-Fi switched off.", dis, slash_cut)
    return out


def wired(dim=False):
    op = DIM if dim else None
    ps = [rr(5.5, 1, 5, 4.5, 1), rr(1, 10.5, 5, 4.5, 1), rr(10, 10.5, 5, 4.5, 1),
          seg(8, 5, 8, 8, 1.5), seg(3.5, 8, 12.5, 8, 1.5),
          seg(3.5, 8, 3.5, 11, 1.5), seg(12.5, 8, 12.5, 11, 1.5)]
    return [(p, op) for p in ps]


def speaker():
    # one shape: the box and the cone
    return "M1 5.5H4L8 2V14L4 10.5H1Z"


VOL_C = (6.5, 8)
VOL_WAVES = [(3.0, 4.5), (5.6, 7.1), (8.2, 9.7)]


def volume(level):
    cx, cy = VOL_C
    out = [speaker()]
    for i, (r0, r1) in enumerate(VOL_WAVES):
        on = i < level
        out.append((sector(cx, cy, r0, r1, -44, 44), None if on else DIM))
    return out


def volume_icons():
    out = {}
    for lvl, name in ((1, "low"), (2, "medium"), (3, "high")):
        out[f"audio-volume-{name}-symbolic"] = (f"Volume {name}.", volume(lvl))
    out["audio-volume-overamplified-symbolic"] = ("Volume above 100%.", volume(3))
    out["audio-volume-muted-symbolic"] = ("Sound muted.",
                                          [speaker(), badge_x(12.25, 8, 2.25, 1.6)])
    return out


# Battery: upright, like the rest of the bar's shapes. The body is a
# 1.5-unit outline; the charge is a solid block inside it with a one-unit
# gap, rising from the bottom in tenths. When charging the battery steps
# left and a bolt stands beside it, so the charge level stays as easy to
# read as when it is not.
def battery(level, charging=False, charged=False, missing=False):
    x0 = 2.5 if (charging or charged) else 4
    w = 9
    top, bot = 3, 15
    body = f"evenodd:{rr(x0, top, w, bot - top, 2)}{rr(x0 + 1.5, top + 1.5, w - 3, bot - top - 3, 0.75)}"
    nub = rr(x0 + 2.75, 1, w - 5.5, 2.5, 0.75)
    out = [body, nub]
    if missing:
        out.append(badge_x(x0 + w / 2, (top + bot) / 2, 1.9, 1.5))
        return out
    inner_top, inner_bot = top + 2.5, bot - 2.5
    h = (inner_bot - inner_top) * level / 100.0
    if level > 0:
        out.append(rr(x0 + 2.5, inner_bot - h, w - 5, h, 0.5 if h > 1 else h / 2))
    if charging or charged:
        out.append("M14.2 4.5L11.2 9.3H13.1L12.3 13.5L15.3 8.7H13.4Z")
    return out


def battery_icons():
    out = {}
    for lvl in range(0, 101, 10):
        out[f"battery-level-{lvl}-symbolic"] = (f"Battery {lvl}%.", battery(lvl))
        if lvl < 100:
            out[f"battery-level-{lvl}-charging-symbolic"] = (
                f"Battery {lvl}%, charging.", battery(lvl, charging=True))
    out["battery-level-100-charged-symbolic"] = ("Battery full, on power.",
                                                 battery(100, charged=True))
    out["battery-missing-symbolic"] = ("No battery.", battery(0, missing=True))
    out["battery-symbolic"] = ("Battery.", battery(60))
    # the older names some programs (waybar, upower) still ask for
    for legacy, lvl in (("full", 100), ("good", 70), ("low", 30), ("caution", 10), ("empty", 0)):
        out[f"battery-{legacy}-symbolic"] = (f"Battery ({legacy}).", battery(lvl))
        out[f"battery-{legacy}-charging-symbolic"] = (
            f"Battery ({legacy}), charging.", battery(lvl, charging=True))
    out["battery-full-charged-symbolic"] = ("Battery full, on power.", battery(100, charged=True))
    return out


def power():
    return [arc_stroke(8, 8.75, 5.5, 1.75, 122, 418), seg(8, 1.5, 8, 7.5, 1.75)]


def keyboard():
    body = rr(0.5, 3.5, 15, 9.5, 2)
    holes = ""
    for i in range(5):
        holes += rr(2 + i * 2.5, 5.5, 1.5, 1.5, 0.3)
    for i in range(4):
        holes += rr(3.25 + i * 2.5, 8, 1.5, 1.5, 0.3)
    holes += rr(4.5, 10.5, 7, 1, 0.3)
    return [f"evenodd:{body}{holes}"]


def brightness():
    out = [circle_path(8, 8, 3)]
    for i in range(8):
        a = math.radians(i * 45)
        out.append(seg(8 + 5.2 * math.cos(a), 8 - 5.2 * math.sin(a),
                       8 + 6.6 * math.cos(a), 8 - 6.6 * math.sin(a), 1.5))
    return out


def app_grid():
    return [circle_path(3 + 5 * c, 3 + 5 * r, 1.6) for r in range(3) for c in range(3)]


def lock():
    shackle = arc_stroke(8, 6, 3.25, 1.5, 0, 180) + seg(4.75, 6, 4.75, 7.5, 1.5) + seg(11.25, 6, 11.25, 7.5, 1.5)
    body = f"evenodd:{rr(2.5, 7, 11, 8, 1.75)}{circle_path(8, 10.5, 1.4, ccw=True)}"
    return [shackle, body]


def airplane():
    return ["M7 1.8C7 1.2 7.45 .8 8 .8S9 1.2 9 1.8V6L14.5 9.2V10.8L9 9.2V12.4L10.8 13.8V15"
            "L8 14.2L5.2 15V13.8L7 12.4V9.2L1.5 10.8V9.2L7 6Z"]


# Window buttons: the glyphs of minimise, maximise, restore and close in
# every title bar. GTK 3, GTK 4, libadwaita, libhandy and Firefox all ask
# the icon theme for these four names, so drawing them here is what makes
# the three buttons look the same in every application. 2 wide, on whole
# pixels so they are sharp at scale 1, on an 8-unit box in the middle of
# the grid, so they sit centred in the round
# buttons gtk.css draws; the strokes are separate parts because two
# overlapping subpaths of one path can cancel where they cross.
def window_icons():
    w = 2
    def ring(x, y, s, r, ri):
        return f"evenodd:{rr(x, y, s, s, r)}{rr(x + w, y + w, s - 2 * w, s - 2 * w, ri)}"
    return {
        "window-minimize-symbolic": ("Minimise a window.", [seg(5, 8, 11, 8, w)]),
        "window-maximize-symbolic": ("Maximise a window.", [ring(4, 4, 8, 2, 0.5)]),
        "window-restore-symbolic": ("Restore a maximised window.",
                                    [seg(7, 4, 12, 4, w), seg(12, 4, 12, 9, w),
                                     ring(3, 6, 7, 1.5, 0.25)]),
        "window-close-symbolic": ("Close a window.",
                                  [seg(5, 5, 11, 11, w), seg(11, 5, 5, 11, w)]),
    }


def symbolic():
    s = {}
    s.update(wifi_icons())
    s["network-wired-symbolic"] = ("Wired network.", wired())
    s["network-wired-disconnected-symbolic"] = ("Wired network, unplugged.",
                                                wired(True) + [badge_x(12.5, 3.25, 2.0, 1.5)],
                                                x_cut(12.5, 3.25, 2.0, 1.5))
    s["network-offline-symbolic"] = ("No network.", wifi(-1) + [badge_x(12.5, 12.5, 2.0, 1.6)],
                                     x_cut(12.5, 12.5, 2.0, 1.6))
    s.update(volume_icons())
    s.update(battery_icons())
    s["system-shutdown-symbolic"] = ("Power.", power())
    s["input-keyboard-symbolic"] = ("On-screen keyboard.", keyboard())
    s["display-brightness-symbolic"] = ("Brightness.", brightness())
    s["view-app-grid-symbolic"] = ("All apps.", app_grid())
    s["system-lock-screen-symbolic"] = ("Lock.", lock())
    s["airplane-mode-symbolic"] = ("Airplane mode.", airplane())
    s.update(window_icons())
    return s


# ── the theme on disk ────────────────────────────────────────────────────

INDEX = """# index.theme - the LP icon theme. GENERATED by desktop/branding/src/icons.py.
#
# App icons are scalable SVGs drawn on a 128 grid; symbolic icons are
# scalable SVGs drawn on the 16 grid the top bar uses. Everything this
# theme does not draw is found in Papirus-Dark, which the base already
# carries and which is what the desktop used before this theme - then
# Adwaita and hicolor, which every GTK application can count on.
[Icon Theme]
Name=LP
Comment=The icons of linux-LP
Inherits=Papirus-Dark,Adwaita,hicolor
Example=utilities-terminal
Directories=scalable/apps,symbolic/status

[scalable/apps]
Context=Applications
Size=128
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/status]
Context=Status
Size=16
MinSize=8
MaxSize=512
Type=Scalable
"""


def write_theme(root):
    """Write desktop/icons/LP. Stale files from an earlier run are removed
    first, so an icon dropped from the tables here is dropped on disk."""
    theme = os.path.join(root, "LP")
    apps = os.path.join(theme, "scalable", "apps")
    stat = os.path.join(theme, "symbolic", "status")
    for d in (apps, stat):
        os.makedirs(d, exist_ok=True)
        for f in os.listdir(d):
            os.unlink(os.path.join(d, f))
    with open(os.path.join(theme, "index.theme"), "w") as f:
        f.write(INDEX)
    names = {}
    for name, what, top, bottom, glyph, aliases in APPS:
        with open(os.path.join(apps, name + ".svg"), "w") as f:
            f.write(app_svg(name, what, top, bottom, glyph))
        names[name] = aliases
    # the logo is an app icon too: the installer, os-release LOGO=, the
    # app grid's "start here"
    with open(os.path.join(apps, "distributor-logo-lp.svg"), "w") as f:
        f.write(mark.svg("distributor-logo-lp.svg",
                         "The LP mark on its tile (os-release LOGO=distributor-logo-lp).",
                         (0, 0, 128, 128), mark.tile_body(uid="lg"), 128, 128))
    names["distributor-logo-lp"] = ["lp-logo", "linux-lp", "distributor-logo", "start-here",
                                    "lp", "org.lp.Welcome"]
    for name, aliases in names.items():
        for a in aliases:
            p = os.path.join(apps, a + ".svg")
            assert not os.path.exists(p), f"{a} is claimed twice"
            os.symlink(name + ".svg", p)
    for name, spec in symbolic().items():
        with open(os.path.join(stat, name + ".svg"), "w") as f:
            f.write(sym(name, *spec))
    return theme


if __name__ == "__main__":
    import sys
    write_theme(sys.argv[1] if len(sys.argv) > 1 else "../../icons")
