#!/usr/bin/env python3
"""gen-motion.py - write motion.css: the springs of design/feel.md as GTK CSS.

The browser mockup on the gui branch moves with linear(): the spring
itself, sampled sixty times. GTK has no linear() - GTK 3.24 and 4.8 know
cubic-bezier() and nothing finer - and no CSS variables either, so the
curves cannot be shared by name the way lp-motion.css shares them.

What this does instead: solve each spring exactly as lp-motion.c does,
then fit the cubic-bezier that stays closest to it over its settle time,
and write the result out as ready-made rules. A bezier cannot turn round
mid-flight - that is what desktop/common/lp-motion.c is for, and anything
that can be interrupted (a panel, the keyboard, a drag) uses that. CSS
transitions are for the rest: hover and press colours, switch knobs,
focus rings, things that go one way and are over.

The error of each fit is printed and written into the file, so a curve
that fits badly says so instead of passing for the spring.

    ./gen-motion.py > motion.css
"""
import math
import sys

# name, k, c, settle ms, what - the table in feel.md §2-2 / lp-motion.c
SPRINGS = [
    ("window", 602.0, 49.1, 340, "window open/close"),
    ("slide", 602.0, 49.1, 340, "workspace, big panels"),
    ("sheet", 856.0, 55.6, 260, "dialogs, quick settings, keyboard"),
    ("expand", 1355.0, 73.6, 240, "accordion, height changes"),
    ("insert", 1435.0, 53.0, 220, "list item in/out (4.5% overshoot)"),
    ("knob", 1614.0, 52.2, 200, "switch knob (6.7% overshoot = 1px)"),
    ("menu", 1599.0, 73.6, 180, "menus, popovers"),
    ("press", 5005.0, 120.3, 130, "pressed control"),
]
DT = 1.0 / 960.0


def spring_curve(k, c, ms):
    """x(t) for a step 0 -> 1, sampled on [0, ms] (semi-implicit Euler at
    960Hz, fine enough that it matches lp-motion.c's closed form to 1e-4)."""
    x = v = t = 0.0
    out = []
    end = ms / 1000.0
    while t <= end + 1e-9:
        out.append((t / end, x))
        a = -k * (x - 1.0) - c * v
        v += a * DT
        x += v * DT
        t += DT
    return out


def bezier_y_at(p, tx):
    x1, y1, x2, y2 = p
    lo, hi = 0.0, 1.0
    for _ in range(40):
        s = (lo + hi) / 2.0
        xs = 3 * (1 - s) ** 2 * s * x1 + 3 * (1 - s) * s * s * x2 + s ** 3
        if xs < tx:
            lo = s
        else:
            hi = s
    s = (lo + hi) / 2.0
    return 3 * (1 - s) ** 2 * s * y1 + 3 * (1 - s) * s * s * y2 + s ** 3


def error(p, curve):
    if not (0.0 <= p[0] <= 1.0 and 0.0 <= p[2] <= 1.0):
        return 1e9
    worst = 0.0
    total = 0.0
    for tx, y in curve[:: max(1, len(curve) // 120)]:
        d = abs(bezier_y_at(p, tx) - y)
        worst = max(worst, d)
        total += d * d
    return total + 50.0 * worst * worst


def fit(curve):
    """Coordinate descent with a shrinking step - four parameters and a
    smooth error surface do not need anything cleverer."""
    best = [0.2, 0.6, 0.3, 1.0]
    e = error(best, curve)
    step = 0.25
    while step > 1e-4:
        improved = False
        for i in range(4):
            for d in (step, -step):
                q = list(best)
                q[i] += d
                eq = error(q, curve)
                if eq < e:
                    best, e, improved = q, eq, True
        if not improved:
            step /= 2.0
    worst = max(abs(bezier_y_at(best, tx) - y) for tx, y in curve)
    return best, worst


def main():
    w = sys.stdout.write
    w("/* motion.css - generated by gen-motion.py. Do not edit.\n"
      " *\n"
      " * The springs of design/feel.md §2 as GTK transitions. GTK has no\n"
      " * linear() and no CSS variables, so each spring is its closest\n"
      " * cubic-bezier, fitted over its settle time; the worst deviation is\n"
      " * in each comment. Exits are 0.7x the entrance.\n"
      " *\n"
      " * CSS is for what goes one way and is over: colours, knobs, focus.\n"
      " * Anything that can be reversed half way - a panel, the keyboard,\n"
      " * a drag - uses desktop/common/lp-motion.c, which turns round\n"
      " * carrying its velocity where a bezier would stop and restart.\n"
      " *\n"
      " * GtkStack page transitions: 260ms. GtkRevealer: 240ms (expand) or\n"
      " * 220ms (list items). Both use GTK's own ease-out curve.\n"
      " *\n"
      " * Reduced motion needs nothing here: the Settings switch turns off\n"
      " * gtk-enable-animations, and GTK then skips every transition.\n"
      " */\n\n")
    fits = {}
    for name, k, c, ms, what in SPRINGS:
        p, worst = fit(spring_curve(k, c, ms))
        fits[name] = (p, ms)
        pts = ", ".join(f"{v:.3f}" for v in p)
        w(f"/* {name}: {what}. {ms}ms in, {round(ms * 0.7)}ms out;"
          f" worst deviation from the spring {worst * 100:.1f}% */\n")
        w(f".lp-m-{name} {{ transition: all {ms}ms cubic-bezier({pts}); }}\n")
        w(f".lp-m-{name}-out {{ transition: all {round(ms * 0.7)}ms"
          f" cubic-bezier({pts}); }}\n\n")

    def bz(name):
        p, _ = fits[name]
        return "cubic-bezier(" + ", ".join(f"{v:.3f}" for v in p) + ")"

    # Widget defaults. Colour changes use press timing: the highlight is
    # applied at once on :active (GTK starts transitions from the current
    # value, so a press shows immediately and the fade-out is what moves).
    w("/* ── defaults for every GTK 3 and GTK 4 window ─────────────── */\n\n")
    w("button, row, .lp-tile {\n"
      f"  transition: background-color 91ms {bz('press')},\n"
      f"              box-shadow 130ms {bz('press')},\n"
      f"              color 130ms {bz('press')};\n"
      "}\n"
      "/* Pressed: no transition in, so touch-down is answered in the\n"
      " * same frame. Only the release above is animated. */\n"
      "button:active, row:active, .lp-tile:active { transition: none; }\n\n")
    w("switch {\n"
      f"  transition: background-color 200ms {bz('knob')};\n"
      "}\n"
      "switch slider {\n"
      f"  transition: all 200ms {bz('knob')};\n"
      "}\n\n")
    w("scale slider {\n"
      f"  transition: box-shadow 130ms {bz('press')};\n"
      "}\n\n")
    w("entry, textview, spinbutton {\n"
      f"  transition: box-shadow 180ms {bz('menu')},\n"
      f"              border-color 180ms {bz('menu')};\n"
      "}\n\n")
    # Popovers, menus and progress bars are not here on purpose: GTK
    # gives neither an opacity to start from nor a width it lays out
    # through CSS, so a transition on them would do nothing and read as
    # if it did. Those move through lp-motion.c in the code that owns them.


if __name__ == "__main__":
    main()
